name: pwallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.4.3
  path: ^1.8.2
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.10
  drift: ^2.2.0
  go_router: ^5.0.5
  http: ^0.13.5
  sqlite3: ^1.9.0
  equatable: ^2.0.5
  hydrated_bloc: ^8.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  crypto: ^3.0.2
  shared_preferences: ^2.0.15
  drift_db_viewer: ^2.0.0
  build_resolvers: ^2.0.10
  fluttertoast: ^8.1.1
  cryptography: ^2.0.5
  encrypt: ^5.0.1
  flutter_native_splash: ^2.2.11
  bloc_test: any
  test: ^1.22.0
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  dio: ^4.0.6

dev_dependencies:
  very_good_analysis: ^3.1.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  android: false
  ios: false
  web: true
  image: assets/pass.png
  color: "#ffffff"
