name: pwallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.4.3
  path: ^1.8.2
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.10
  drift: ^2.2.0
  go_router: ^5.0.5
  http: ^0.13.5
  sqlite3: ^1.9.0
  equatable: ^2.0.5
  hydrated_bloc: ^8.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  crypto: ^3.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.1.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.3.0
flutter:
  uses-material-design: true
