import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'ipdata.freezed.dart';
// optional: Since our IpData class is serializable, we must add this line.
// But if IpData was not serializable, we could skip it.
part 'ipdata.g.dart';

@freezed
class IpData with _$IpData {
  const factory IpData({
    String? country,
    String? regionName,
    @JsonKey(name: 'query') String? ip,
  }) = _IpData;

  factory IpData.fromJson(Map<String, Object?> json) => _$IpDataFromJson(json);
}
